version: 2
updates:
  # ðŸ“¦ Actualizaciones para Maven
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    allow:
      - dependency-type: "all"   # directas e indirectas
    commit-message:
      prefix: "deps"             # Prefijo del mensaje del commit
    pull-request-branch-name:
      separator: "-"             # Ajusta el formato interno

  #  Actualizar GitHub Actions tambiÃ©n
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
